"""Add additional_info column to audit_log table

Revision ID: 06575c180076
Revises: faba4da103fd
Create Date: 2025-09-09 01:42:14.186536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06575c180076'
down_revision = 'faba4da103fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_info', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_column('additional_info')

    # ### end Alembic commands ###
