"""Add company_email field

Revision ID: 50c15c74417c
Revises: 7484f971e4ea
Create Date: 2025-09-23 09:46:40.493934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50c15c74417c'
down_revision = '7484f971e4ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        # Step 1: Add column as nullable first
        batch_op.add_column(sa.Column('company_email', sa.String(length=120), nullable=True))
    
    # Step 2: Populate existing records with safe unique values
    connection = op.get_bind()
    
    # First, try to use company code (guaranteed unique)
    connection.execute(sa.text("""
        UPDATE company 
        SET company_email = 'admin@' || LOWER(REGEXP_REPLACE(COALESCE(code, ''), '[^a-z0-9]+', '', 'g')) || '.workly.com'
        WHERE company_email IS NULL AND code IS NOT NULL AND code != ''
    """))
    
    # For any remaining companies without valid codes, use ID (guaranteed unique)
    connection.execute(sa.text("""
        UPDATE company 
        SET company_email = 'admin+' || id::text || '@workly.com'
        WHERE company_email IS NULL
    """))
    
    # Step 3: Make the column non-nullable and add unique constraint
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('company_email', nullable=False)
        batch_op.create_unique_constraint('uq_company_company_email', ['company_email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_constraint('uq_company_company_email', type_='unique')
        batch_op.drop_column('company_email')

    # ### end Alembic commands ###
