"""Add Notion module and integration models

Revision ID: 7484f971e4ea
Revises: 06575c180076
Create Date: 2025-09-09 20:14:15.246922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7484f971e4ea'
down_revision = '06575c180076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module_notion', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_pref_notion', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('admin_pref_notion')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('module_notion')

    # ### end Alembic commands ###
