"""Add missing cash_session_id column to sale table

Revision ID: faba4da103fd
Revises: 
Create Date: 2025-09-09 01:33:37.835507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faba4da103fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_audit_log_company_id'))
        batch_op.drop_index(batch_op.f('idx_audit_log_table_record'))

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('contact_phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('contact_whatsapp',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('contact_address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)

    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_inventory_item_barcode'))
        batch_op.drop_index(batch_op.f('idx_inventory_item_company_id'))
        batch_op.drop_index(batch_op.f('idx_inventory_item_sku'))
        batch_op.drop_index(batch_op.f('idx_inventory_item_warehouse_id'))

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cash_session_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'cash_session', ['cash_session_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'empleado'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'empleado'::character varying"))

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cash_session_id')

    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_inventory_item_warehouse_id'), ['warehouse_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_inventory_item_sku'), ['sku'], unique=False)
        batch_op.create_index(batch_op.f('idx_inventory_item_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_inventory_item_barcode'), ['barcode'], unique=False)

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('contact_address',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('contact_whatsapp',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('contact_phone',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_audit_log_table_record'), ['table_name', 'record_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_audit_log_company_id'), ['company_id'], unique=False)

    # ### end Alembic commands ###
